# Generated by Django 5.0.7 on 2024-08-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
