# Generated by Django 5.0.7 on 2024-08-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NHSApp', '0002_post_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
    ]
