# Generated by Django 5.0.7 on 2024-08-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHSApp', '0004_post_comment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
