# Generated by Django 5.0.7 on 2024-08-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHSApp', '0005_post_downvote_post_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
