# Generated by Django 5.1 on 2024-08-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHSApp', '0007_remove_post_downvote_remove_post_upvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NHSApp.comment'),
        ),
    ]
