# Generated by Django 5.1 on 2024-08-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NHSApp', '0008_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('일반', 'general'), ('질문', 'question'), ('공지', 'notice')], default='일반', max_length=10),
        ),
    ]
